DA: false
LPN: false
adain: a
alpha: 1
batchsize: 8
block: 6
btnk:
- 0
- 1
- 1
- 0
- 0
- 0
- 0
circle: false
color_jitter: false
conv_norm: none
data_dir: /data/train
droprate: 0.5
erasing_p: 0
experiment_name: fanet_best_reproduce
extra_Google: true
focal: true
fp16: false
gpu_ids: '0'
h: 256
iaa: true
lr: 0.005
moving_avg: 1.0
multi_weather: true
name: fanet_best_reproduce
nclasses: 701
norm: spade
pad: 10
pool: avg
reptile: true
resume: false
seed: 1
share: true
stride: 1
style_loss: false
train_all: false
use_NAS: false
use_dense: false
use_res101: false
use_vgg: false
views: 3
w: 256
warm_epoch: 0
